apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: trueberryless-org
    namespace: trueberryless-org
spec:
    secretName: trueberryless-org
    issuerRef:
        name: acme-issuer
        kind: ClusterIssuer
    dnsNames:
        - "trueberryless-org.trueberryless.org"
