apiVersion: apps/v1
kind: Deployment
metadata:
  name: trueberryless-org
  namespace: trueberryless-org
  labels:
    app: trueberryless-org
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trueberryless-org
  template:
    metadata:
      labels:
        app: trueberryless-org
    spec:
      containers:
        - name: trueberryless-org
          image: "trueberryless/trueberryless-org:main-858b4923015478abbfdef1cfcf2e46a87f9af713"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
